# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
$schema: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
blocks:
    - alignment: left
      segments:
        - background: '#3b4252'
          foreground: '#e5e9f0'
          properties:
            style: folder
          style: powerline 
          template: ' {{ .Path }} '
          type: path
        - foreground: '#D0666F'
          properties:
            branch_icon: ""
          style: plain
          template: <#5FAAE8>git:(</>{{ .HEAD }}<#5FAAE8>)</>
          type: git
        - foreground: '#BF616A'
          style: plain
          template: ' ✗'
          type: exit
      type: prompt
final_space: true
version: 2

