# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
$schema: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
blocks:
    - alignment: left
      segments:
        - background: '#4c566a'
          foreground: 'white'
          properties:
            branch_icon: ""
            fetch_upstream_icon: true
          style: powerline
          template: " \uf1d2 {{ .RepoName }}"
          type: git
        - background: 'green'
          foreground: 'black'
          properties:
            branch_icon: ""
            branch_max_length: 25
            fetch_stash_count: true
            fetch_status: true
            fetch_upstream_icon: true
          style: powerline 
          powerline_symbol: "\ue0b0"
          background_templates:
            - "{{ if or (.Working.Changed) (.Staging.Changed) }}red{{ end }}"
            - "{{ if or (gt .Behind 0) (gt .Ahead 0)}}yellow{{ end }}"
          foreground_templates:
            - "{{ if or (.Working.Changed) (.Staging.Changed) }}white{{ end }}"
          template: " {{ .HEAD }}"
          type: git
        - background: 'blue'
          foreground: '#e5e9f0'
          properties:
            style: folder
          style: powerline 
          powerline_symbol: "\ue0b0"
          template: ' {{ .Path }}/ '
          type: path
        - foreground: '#BF616A'
          style: plain
          template: ' ✗'
          type: exit
      type: prompt
final_space: true
version: 2

